# This is a basic workflow to help you get started with Actions

name: blank_2

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Change something
        run: echo "Simulate change file version" > README.md
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        id: commit_changes
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "[AUTO-COMMIT] foo/bar replace"
          target_branch: version/update
      - name: Create pull request
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: "**Automated pull request**<br><br>Replaced foo/bar"
          title: ${{ github.event.commits[0].message }}
          source_branch: ${{ steps.commit_changes.outputs.branch_name }}
          target_branch: ${{ steps.extract_branch.outputs.branch_name }}
