name: build-connect

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo "Run workflow with version ${{ github.event.inputs.version }}"
        id: one-line-script
