name: build-connect

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo This workflow will be used to build Wecan Connect Docker image
        id: one-line-script
